title = "http method get cookies"
description = "http method get cookies"

[request]
method = "get"
url = "http://httpbin.org/cookies"
body = """
{
    "hello": "world"
}
"""
cookie = "uid=123"
[request.header]
Content-Type = "application/json"


[assert]
status = "ok"
statusCode = 200
contentLength_gt = 0
contentType = "application/json"

[[assert.json]]
path = "cookies.uid"
value =  "123"
