title = "http method get"
description = "http method get"

[request]
method = "get"
url = "http://localhost:1200/get?a=1&b=2"


[assert]
status = "ok"
statusCode = 200
contentLength_gt = 180
contentType = "application/json"
