title = "http method post form"
description = "http method post form"

[request]
method = "post"
url = "http://httpbin.org/post"
body = "@post_form_body_file"
[request.header]
Content-Type = "application/x-www-form-urlencoded"


[assert]
status = "ok"
statusCode = 200
contentLength_gt = 180
contentType = "application/json"
