title = "http method options"
description = "http method options"

[request]
method = "options"
url = "http://httpbin.org/get"


[assert]
status = "ok"
statusCode = 200
contentLength_gt = 180
contentType = "application/json"
