title = "http method post"
description = "http method post"

[request]
method = "post"
url = "http://httpbin.org/post"
body = "@./post_body_file"
[request.header]
Content-Type = "application/json"


[assert]
status = "ok"
statusCode = 200
contentLength_gt = 180
contentType = "application/json"
